/**
 * FUTURE LANGUAGE: English (en)
 *
 * TODO: When adding English support for Google Play expansion:
 * 1. Move this object back into strings.ts
 * 2. Add 'en' back to AppLanguage type
 * 3. Add 'en' back to LANGUAGE_STRINGS record
 * 4. Restore LANGUAGE_OPTIONS in strings.ts
 * 5. Restore language picker in OnboardingScreen and SettingsScreen
 * 6. Restore setLanguage in LanguageContext
 * 7. Translate all exercise content (questions/options/hints) in module files
 * 8. Note: English uses different Excel function names (SUM vs SOMME, IF vs SI, etc.)
 */

import { AppStrings } from '../strings';

export const ENGLISH: AppStrings = {
  langName: 'English',
  isRTL: false,
  tabHome: 'Home',
  tabModules: 'Courses',
  tabLeaderboard: 'Leaderboard',
  tabBadges: 'Badges',
  tabSimulator: 'Simulator',
  langSelectTitle: 'Choose your language',
  langSelectSub: 'Choose your language',
  onboard1Title: 'Welcome to Almdoun Learning! 🎉',
  onboard1Desc: 'Learn Excel by playing! Every lesson = XP + new badge!',
  onboard2Title: 'Learn Excel by playing! 🎮',
  onboard2Desc: 'Lessons, exercises, mini-games and badges – all together!',
  onboard3Title: 'Enter your name and start! 🚀',
  onboard3Desc: 'Enter your name and choose your avatar.',
  nameLabel: 'Your name:',
  namePlaceholder: 'Enter your name...',
  avatarLabel: 'Choose your avatar:',
  startBtn: 'Start now! 🚀',
  nextBtn: 'Next →',
  loading: 'Loading...',
  greeting: 'Hello! 👋',
  gamesTitle: '🎮 Games & Challenges',
  dailyChallengeTitle: 'Daily Challenge 🔥',
  dailyChallengeDesc: 'Solve 5 questions and earn XP!',
  quickQuizTitle: 'Quick Quiz ⚡',
  quickQuizDesc: 'Different questions every time',
  myModules: 'My courses 📚',
  checkBtn: 'Check Answer →',
  nextQ: 'Next Question →',
  finishBtn: '🏁 See Results!',
  correct: 'Correct! 🎉',
  wrong: 'Wrong! Try again 😊',
  showHint: '💡 Hint',
  hintLabel: '💡 Hint:',
  trueBtn: 'True ✓',
  falseBtn: 'False ✗',
  correctAnswer: 'Correct answer:',
  reorderLabel: 'Reorder the parts:',
  fillBlankPlaceholder: 'Type your answer...',
  correctOrderLabel: 'Correct order:',
  result3: 'Excellent! You are a star! ⭐⭐⭐',
  result2: 'Good job! Keep going! ⭐⭐',
  result1: 'Almost there, try again! 💪⭐',
  result0: 'Try again! You can do it! 😊',
  xpEarned: 'XP earned:',
  nextLesson: 'Next lesson →',
  retryBtn: 'Retry',
  backHome: 'Home',
  simulatorTitle: 'Excel Simulator 🖥️',
  simulatorHint: 'Tap a cell, enter a value or formula (start with =)',
  fnSum: 'SUM',
  fnAvg: 'AVERAGE',
  fnIf: 'IF',
  fnCount: 'COUNT',
  fnCountIf: 'COUNTIF',
  fnMax: 'MAX',
  fnMin: 'MIN',
  fnLeft: 'LEFT',
  fnRight: 'RIGHT',
  fnUpper: 'UPPER',
  challengeTitle: 'Daily Challenge',
  dailyChallenge: 'Challenge',
  hintCost: '(-10 pts)',
  noHints: 'No hints left!',
  challengeDone: 'Done for today ✅',
  challengeNextIn: 'New one tomorrow 🌙',
  tabGames: 'Games 🎮',
  gameCellNavName: 'Cell Navigator',
  gameCellNavDesc: 'Find the cell in the Excel grid!',
  gameFormulaName: 'Formula Fixer',
  gameFormulaDesc: 'Fix the broken Excel formulas!',
  gameSpeedQuizName: 'Speed Quiz',
  gameSpeedQuizDesc: 'Answer fast and earn XP!',
  gamePlayBtn: 'Play Now! 🚀',
  gameRound: 'Round',
  gameScore: 'Score',
  gameOver: '🏁 Game Over!',
  gameTapCell: 'Tap the cell:',
  gameTimeLeft: 'Time left:',
  gameStreakLabel: 'Streak 🔥',
  gameXpBonus: 'XP bonus!',
  gameNext: 'Next →',
  gameCellNameQuestion: 'What is this cell called? 🟩',
  gameFixFormula: '🔧 Fix this formula:',
  friendArrowHint: '⬇ Show this QR to your friend ⬇',
  continueLabel: 'Continue →',
  modulesSubtitle: 'Start from the beginning or continue where you left off!',
  miniGamesTitle: '🎮 Mini Games',
  diffEasy: 'Beginner',
  diffMedium: 'Medium',
  diffHard: 'Fast',
  gameTipTitle: '💡 How to earn more XP?',
  gameTipText: '→ Answer fast = XP bonus\n→ Longer streak = bigger multiplier\n→ Every challenge = new XP!',
  settingsTitle: 'Settings ⚙️',
  settingsProfileSection: 'Profile',
  settingsProfileLabel: 'Active profile',
  settingsSwitchProfile: 'Switch profile',
  settingsGenderSection: 'Gender',
  settingsMale: 'Boy',
  settingsFemale: 'Girl',
  settingsSoundSection: 'Sound & Vibration',
  settingsSoundLabel: '🔊 Sound',
  settingsVibration: '📳 Vibration',
  settingsAboutSection: 'About Almdoun Learning',
  settingsSchool: 'School',
  settingsSubject: 'Subject',
  moduleDone: '✅ Done',
  lessonConceptLabel: 'Concept',
  lessonStepsLabel: 'Steps:',
  lessonFormulaLabel: '📐 Formula:',
  lessonExampleLabel: '📌 Example:',
  lessonShortcutsLabel: '⌨️ Keyboard shortcuts:',
  lessonTipLabel: '💡 Tip:',
  lessonMiniGame: '🎮 Mini-Game!',
  leaderboardTitle: 'Leaderboard 🏆',
  leaderboardEmpty: 'No players yet. Start learning!',
  leaderboardBotLabel: '🤖 Demo',
  leaderboardOnlyOne: 'Ask friends to install the app to see the ranking! 🏆',
  leaderboardYouHere: '← you',
  darkMode: '🌙 Dark Mode',
  searchModules: '🔍 Search for a module...',
  shareProgress: '📤 Share',
  streakCalendar: '🔥 Active Days',
  classChallengeTitle: '👨‍🏫 Class Challenge',
  classChallengeSubtitle: 'Choose difficulty and number of questions',
  classChallengeQRInstruction: 'Each student scans this QR to play',
  classChallengePlaySelf: '▶ Play yourself',
  classChallengeResultTitle: 'Your result 🎯',
  classChallengeShareHint: 'Show this QR to the class',
  classChallengeDone: '✓ Done',
  friendChallengeTitle: '🤝 Friend Challenge',
  friendCreate: '🎯 Create Challenge',
  friendCreateSub: 'Play and send the QR to your friend',
  friendScan: '📷 Scan Challenge',
  friendScanSub: "Scan your friend's QR and play",
  friendHowTitle: 'How it works?',
  friendStep1: '① Play questions – get your score',
  friendStep2: '② Show the QR code to your friend',
  friendStep3: '③ Friend scans and plays the same questions',
  friendStep4: '④ Compare scores – winner gets bonus XP! 🏆',
  friendShowQR: 'Show this QR to your friend',
  friendQRInstruction: 'Your friend must scan this code to play',
  friendDone: '✓ Done',
  friendScanTitle: "📷 Scan Friend's Challenge",
  friendScanInstruction: "Point the camera at your friend's QR",
  friendScanError: 'Invalid QR code. Try again.',
  friendPermissionTitle: 'Camera Access Required',
  friendPermissionBtn: 'Allow Camera',
  friendResultTitle: 'Results 🏆',
  friendWinner: '🥇 Winner!',
  friendDraw: "🤝 It's a draw!",
  friendYou: 'You',
  friendFriend: 'Friend',
  friendPlayAgain: '🔄 Play Again',
  profileDeleteTitle: 'Delete Profile?',
  profileDeleteMsg: 'Are you sure you want to delete this profile? This action cannot be undone.',
  profileDeleteNo: 'No',
  profileDeleteYes: 'Yes, Delete',
  profileWhoTitle: 'Who are you? 👤',
  profileChooseLabel: 'Choose your profile:',
  profileHoldHint: 'Hold to delete',
  profileNewBtn: 'New Profile',
  classChallengeCountSuffix: 'questions',
  classChallengeOrDivider: 'or',
  locked: 'Locked 🔒',
  back: '← Back',
  englishNote: 'In English mode, Excel functions use English names: SUM, AVERAGE, IF, COUNT...',
  level: 'Level',
  streak: 'Days',
};
