/**
 * FUTURE LANGUAGE: French (fr)
 *
 * TODO: When adding French support for Google Play expansion:
 * 1. Move this object back into strings.ts
 * 2. Add 'fr' back to AppLanguage type
 * 3. Add 'fr' back to LANGUAGE_STRINGS record
 * 4. Restore LANGUAGE_OPTIONS in strings.ts
 * 5. Restore language picker in OnboardingScreen and SettingsScreen
 * 6. Restore setLanguage in LanguageContext
 * 7. Translate all exercise content (questions/options/hints) in module files
 */

import { AppStrings } from '../strings';

export const FRENCH: AppStrings = {
  langName: 'Français',
  isRTL: false,
  tabHome: 'Accueil',
  tabModules: 'Cours',
  tabLeaderboard: 'Classement',
  tabBadges: 'Badges',
  tabSimulator: 'Simulateur',
  langSelectTitle: 'Choisissez votre langue',
  langSelectSub: 'Choose your language',
  onboard1Title: 'Bienvenue sur ExcelStar! 🎉',
  onboard1Desc: 'Apprenez Excel en jouant! Chaque leçon = XP + badge!',
  onboard2Title: 'Apprenez Excel en jouant! 🎮',
  onboard2Desc: 'Leçons, exercices, mini-jeux et badges – tout ensemble!',
  onboard3Title: 'Entrez votre nom et commencez! 🚀',
  onboard3Desc: 'Entrez votre nom et choisissez votre avatar.',
  nameLabel: 'Votre prénom:',
  namePlaceholder: 'Entrez votre prénom...',
  avatarLabel: 'Choisissez votre avatar:',
  startBtn: 'Commencer! 🚀',
  nextBtn: 'Suivant →',
  loading: 'Chargement...',
  greeting: 'Bonjour! 👋',
  gamesTitle: '🎮 Jeux & Défis',
  dailyChallengeTitle: 'Défi du jour 🔥',
  dailyChallengeDesc: 'Résolvez 5 questions et gagnez des XP!',
  quickQuizTitle: 'Quiz rapide ⚡',
  quickQuizDesc: 'Questions différentes à chaque fois',
  myModules: 'Mes cours 📚',
  checkBtn: 'Vérifier →',
  nextQ: 'Question suivante →',
  finishBtn: '🏁 Voir le résultat!',
  correct: 'Correct! 🎉',
  wrong: 'Incorrect! Courage 😊',
  showHint: '💡 Indice',
  hintLabel: '💡 Indice:',
  trueBtn: 'Vrai ✓',
  falseBtn: 'Faux ✗',
  correctAnswer: 'Bonne réponse:',
  reorderLabel: 'Réorganisez les parties:',
  fillBlankPlaceholder: 'Écrivez votre réponse...',
  correctOrderLabel: 'Ordre correct:',
  result3: 'Excellent! Vous êtes une star! ⭐⭐⭐',
  result2: 'Bien! Continuez! ⭐⭐',
  result1: 'Pas mal, réessayez! 💪⭐',
  result0: 'Réessayez! Courage! 😊',
  xpEarned: 'XP gagnés:',
  nextLesson: 'Leçon suivante →',
  retryBtn: 'Réessayer',
  backHome: 'Accueil',
  simulatorTitle: 'Simulateur Excel 🖥️',
  simulatorHint: 'Touchez une cellule, entrez une valeur ou formule (commence par =)',
  fnSum: 'SOMME',
  fnAvg: 'MOYENNE',
  fnIf: 'SI',
  fnCount: 'NB',
  fnCountIf: 'NB.SI',
  fnMax: 'MAX',
  fnMin: 'MIN',
  fnLeft: 'GAUCHE',
  fnRight: 'DROITE',
  fnUpper: 'MAJUSCULE',
  challengeTitle: 'Défi du jour',
  dailyChallenge: 'Défi',
  hintCost: '(-10 pts)',
  noHints: "Plus d'indices!",
  challengeDone: "Défi terminé aujourd'hui ✅",
  challengeNextIn: 'Nouveau demain 🌙',
  tabGames: 'Jeux 🎮',
  gameCellNavName: 'Cell Navigator',
  gameCellNavDesc: 'Trouvez la cellule dans le tableau Excel!',
  gameFormulaName: 'Formula Fixer',
  gameFormulaDesc: 'Corrigez les formules Excel!',
  gameSpeedQuizName: 'Speed Quiz',
  gameSpeedQuizDesc: 'Répondez vite et gagnez des XP!',
  gamePlayBtn: 'Jouer! 🚀',
  gameRound: 'Round',
  gameScore: 'Score',
  gameOver: '🏁 Fin!',
  gameTapCell: 'Tapez la cellule:',
  gameTimeLeft: 'Temps restant:',
  gameStreakLabel: 'Série 🔥',
  gameXpBonus: 'XP bonus!',
  gameNext: 'Suivant →',
  gameCellNameQuestion: "Comment s'appelle cette cellule? 🟩",
  gameFixFormula: '🔧 Corrige cette formule:',
  friendArrowHint: '⬇ Montre ce QR à ton ami ⬇',
  continueLabel: 'Continuer →',
  modulesSubtitle: "Recommence ou continue là où tu t'es arrêté!",
  miniGamesTitle: '🎮 Mini Jeux',
  diffEasy: 'Débutant',
  diffMedium: 'Moyen',
  diffHard: 'Rapide',
  gameTipTitle: '💡 Comment gagner plus de XP?',
  gameTipText: '→ Répondre vite = bonus XP\n→ Série plus longue = multiplicateur plus grand\n→ Chaque défi = nouveau XP!',
  settingsTitle: 'Paramètres ⚙️',
  settingsProfileSection: 'Profil',
  settingsProfileLabel: 'Profil actif',
  settingsSwitchProfile: 'Changer de profil',
  settingsGenderSection: 'Genre',
  settingsMale: 'Garçon',
  settingsFemale: 'Fille',
  settingsSoundSection: 'Son & Vibration',
  settingsSoundLabel: '🔊 Son',
  settingsVibration: '📳 Vibration',
  settingsAboutSection: 'À propos',
  settingsSchool: 'École',
  settingsSubject: 'Matière',
  moduleDone: '✅ Terminé',
  lessonConceptLabel: 'Concept',
  lessonStepsLabel: 'Étapes:',
  lessonFormulaLabel: '📐 Formule:',
  lessonExampleLabel: '📌 Exemple:',
  lessonShortcutsLabel: '⌨️ Raccourcis clavier:',
  lessonTipLabel: '💡 Astuce:',
  lessonMiniGame: '🎮 Mini-Jeu!',
  leaderboardTitle: 'Classement 🏆',
  leaderboardEmpty: 'Pas encore de joueurs. Commencez à apprendre!',
  leaderboardBotLabel: '🤖 Demo',
  leaderboardOnlyOne: "Invite tes amis à installer l'app pour voir le classement! 🏆",
  leaderboardYouHere: '← toi ici',
  darkMode: '🌙 Mode sombre',
  searchModules: '🔍 Rechercher un cours...',
  shareProgress: '📤 Partager',
  streakCalendar: '🔥 Jours actifs',
  classChallengeTitle: '👨‍🏫 Défi de Classe',
  classChallengeSubtitle: 'Choisissez la difficulté et le nombre de questions',
  classChallengeQRInstruction: 'Chaque élève scanne ce QR pour jouer',
  classChallengePlaySelf: '▶ Jouer soi-même',
  classChallengeResultTitle: 'Ton résultat 🎯',
  classChallengeShareHint: 'Montre ce QR à la classe',
  classChallengeDone: '✓ Retour',
  friendChallengeTitle: '🤝 Défi Ami',
  friendCreate: '🎯 Créer un Défi',
  friendCreateSub: 'Joue et envoie le QR à ton ami',
  friendScan: '📷 Scanner un Défi',
  friendScanSub: 'Scanne le QR de ton ami et joue',
  friendHowTitle: 'Comment ça marche?',
  friendStep1: '① Joue les questions – obtiens ton score',
  friendStep2: '② Montre le QR à ton ami',
  friendStep3: '③ Ton ami scanne et joue les mêmes questions',
  friendStep4: '④ Comparez les scores – le gagnant obtient + XP! 🏆',
  friendShowQR: 'Montre ce QR à ton ami',
  friendQRInstruction: 'Ton ami doit scanner ce code pour jouer',
  friendDone: '✓ Retour',
  friendScanTitle: '📷 Scanner le Défi',
  friendScanInstruction: "Pointe la caméra sur le QR de ton ami",
  friendScanError: 'QR invalide. Réessaie.',
  friendPermissionTitle: 'Accès Caméra requis',
  friendPermissionBtn: 'Autoriser la Caméra',
  friendResultTitle: 'Résultats 🏆',
  friendWinner: '🥇 Gagnant!',
  friendDraw: '🤝 Égalité!',
  friendYou: 'Toi',
  friendFriend: 'Ami',
  friendPlayAgain: '🔄 Rejouer',
  profileDeleteTitle: 'Supprimer le profil?',
  profileDeleteMsg: 'Voulez-vous supprimer ce profil? Cette action est irréversible.',
  profileDeleteNo: 'Non',
  profileDeleteYes: 'Oui, supprimer',
  profileWhoTitle: 'Qui es-tu? 👤',
  profileChooseLabel: 'Choisis ton profil:',
  profileHoldHint: 'Maintenir pour supprimer',
  profileNewBtn: 'Nouveau profil',
  classChallengeCountSuffix: 'questions',
  classChallengeOrDivider: 'ou',
  locked: 'Verrouillé 🔒',
  back: '← Retour',
  englishNote: '',
  level: 'Niveau',
  streak: 'Jours',
};
